//! Cross-language compatibility tests for ML-DSA-65.
//!
//! Verifies that the `fips204` Rust crate and `@noble/post-quantum` TypeScript
//! library produce byte-identical outputs when given the same deterministic
//! inputs, confirming full FIPS 204 compliance and SDK interoperability.
//!
//! Fixture: `tests/fixtures/mldsa65-cross-lang.json`
//! Generated by: `cargo run -p shell-crypto --bin gen_mldsa_vectors`

use fips204::ml_dsa_65;
use fips204::traits::{KeyGen, SerDes, Signer as FipsSigner, Verifier as FipsVerifier};
use serde::Deserialize;

#[derive(Deserialize)]
struct SignatureVector {
    sign_seed_hex: String,
    signature_hex: String,
    signature_len: usize,
}

#[derive(Deserialize)]
struct KeySizes {
    public_key_len: usize,
    secret_key_len: usize,
    signature_len: usize,
}

#[derive(Deserialize)]
struct Fixture {
    keygen_seed_hex: String,
    public_key_hex: String,
    secret_key_hex: String,
    message_hex: String,
    rust_vector: SignatureVector,
    noble_vector: SignatureVector,
    key_sizes: KeySizes,
}

fn hex_to_bytes(hex: &str) -> Vec<u8> {
    let clean = hex.trim_start_matches("0x");
    (0..clean.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&clean[i..i + 2], 16).expect("valid hex"))
        .collect()
}

fn load_fixture() -> Fixture {
    let json = include_str!("fixtures/mldsa65-cross-lang.json");
    serde_json::from_str(json).expect("valid fixture JSON")
}

// ─── Key generation ──────────────────────────────────────────────────────────

#[test]
fn cross_lang_keygen_seed_produces_identical_keys() {
    let fixture = load_fixture();
    let seed_bytes = hex_to_bytes(&fixture.keygen_seed_hex);
    let seed: [u8; 32] = seed_bytes.try_into().expect("32-byte keygen seed");

    let (pk, sk) = ml_dsa_65::KG::keygen_from_seed(&seed);
    let pk_bytes = pk.into_bytes();
    let sk_bytes = sk.into_bytes();

    assert_eq!(
        hex::encode(pk_bytes),
        fixture.public_key_hex,
        "public key must match Noble's output for the same seed"
    );
    assert_eq!(
        hex::encode(sk_bytes),
        fixture.secret_key_hex,
        "secret key must match Noble's output for the same seed"
    );
    assert_eq!(pk_bytes.len(), fixture.key_sizes.public_key_len);
    assert_eq!(sk_bytes.len(), fixture.key_sizes.secret_key_len);
    assert_eq!(fixture.key_sizes.signature_len, 3309);
}

// ─── Signature production ─────────────────────────────────────────────────────

#[test]
fn cross_lang_rust_sig_matches_fixture() {
    let fixture = load_fixture();
    let sk_bytes: [u8; 4032] = hex_to_bytes(&fixture.secret_key_hex)
        .try_into()
        .expect("4032-byte secret key");
    let msg = hex_to_bytes(&fixture.message_hex);
    let sign_seed: [u8; 32] = hex_to_bytes(&fixture.rust_vector.sign_seed_hex)
        .try_into()
        .expect("32-byte sign seed");

    let sk = ml_dsa_65::PrivateKey::try_from_bytes(sk_bytes).expect("valid sk");
    let sig = sk
        .try_sign_with_seed(&sign_seed, &msg, &[])
        .expect("sign succeeded");

    assert_eq!(sig.len(), fixture.rust_vector.signature_len);
    assert_eq!(
        hex::encode(sig),
        fixture.rust_vector.signature_hex,
        "Rust deterministic sig must match committed fixture vector"
    );
}

#[test]
fn cross_lang_noble_sig_matches_fixture() {
    // Verify that Noble's committed signature is also deterministically reproducible.
    // Noble uses extraEntropy:false → rnd=[0;32], which maps to sign_seed=[0;32] in fips204.
    let fixture = load_fixture();
    let sk_bytes: [u8; 4032] = hex_to_bytes(&fixture.secret_key_hex)
        .try_into()
        .expect("4032-byte secret key");
    let msg = hex_to_bytes(&fixture.message_hex);
    let sign_seed: [u8; 32] = hex_to_bytes(&fixture.noble_vector.sign_seed_hex)
        .try_into()
        .expect("32-byte sign seed");

    let sk = ml_dsa_65::PrivateKey::try_from_bytes(sk_bytes).expect("valid sk");
    let sig = sk
        .try_sign_with_seed(&sign_seed, &msg, &[])
        .expect("sign succeeded");

    assert_eq!(sig.len(), fixture.noble_vector.signature_len);
    assert_eq!(
        hex::encode(sig),
        fixture.noble_vector.signature_hex,
        "Noble and Rust produce identical sig for same (key, rnd=[0;32], ctx=[])"
    );
}

// ─── Cross-language verification ─────────────────────────────────────────────

#[test]
fn cross_lang_rust_verifies_noble_sig() {
    let fixture = load_fixture();
    let pk_bytes: [u8; 1952] = hex_to_bytes(&fixture.public_key_hex)
        .try_into()
        .expect("1952-byte public key");
    let msg = hex_to_bytes(&fixture.message_hex);
    let noble_sig: [u8; 3309] = hex_to_bytes(&fixture.noble_vector.signature_hex)
        .try_into()
        .expect("3309-byte signature");

    let pk = ml_dsa_65::PublicKey::try_from_bytes(pk_bytes).expect("valid pk");
    assert!(
        pk.verify(&msg, &noble_sig, &[]),
        "Rust must verify Noble-generated ML-DSA-65 signature"
    );
}

#[test]
fn cross_lang_rust_verifies_rust_sig() {
    let fixture = load_fixture();
    let pk_bytes: [u8; 1952] = hex_to_bytes(&fixture.public_key_hex)
        .try_into()
        .expect("1952-byte public key");
    let msg = hex_to_bytes(&fixture.message_hex);
    let rust_sig: [u8; 3309] = hex_to_bytes(&fixture.rust_vector.signature_hex)
        .try_into()
        .expect("3309-byte signature");

    let pk = ml_dsa_65::PublicKey::try_from_bytes(pk_bytes).expect("valid pk");
    assert!(
        pk.verify(&msg, &rust_sig, &[]),
        "Rust must verify its own committed fixture signature"
    );
}

#[test]
fn cross_lang_wrong_msg_fails_verification() {
    let fixture = load_fixture();
    let pk_bytes: [u8; 1952] = hex_to_bytes(&fixture.public_key_hex)
        .try_into()
        .expect("1952-byte public key");
    let wrong_msg = b"wrong message";
    let rust_sig: [u8; 3309] = hex_to_bytes(&fixture.rust_vector.signature_hex)
        .try_into()
        .expect("3309-byte signature");

    let pk = ml_dsa_65::PublicKey::try_from_bytes(pk_bytes).expect("valid pk");
    assert!(
        !pk.verify(wrong_msg, &rust_sig, &[]),
        "verification must fail for wrong message"
    );
}

// ─── MlDsaSigner/MlDsaVerifier integration ───────────────────────────────────

#[test]
fn cross_lang_mldsa_verifier_accepts_noble_sig() {
    use shell_crypto::{MlDsaVerifier, PQSignature, SignatureType, Verifier};

    let fixture = load_fixture();
    let pk_bytes = hex_to_bytes(&fixture.public_key_hex);
    let msg = hex_to_bytes(&fixture.message_hex);
    let noble_sig_bytes = hex_to_bytes(&fixture.noble_vector.signature_hex);

    let sig = PQSignature::new(SignatureType::MlDsa65, noble_sig_bytes);
    let verifier = MlDsaVerifier;

    assert!(
        verifier
            .verify(&pk_bytes, &msg, &sig)
            .expect("no crypto error"),
        "MlDsaVerifier must accept Noble-generated signature"
    );
}

#[test]
fn cross_lang_mldsa_signer_produces_verifiable_sig() {
    use shell_crypto::{MlDsaSigner, MlDsaVerifier, Signer, Verifier};

    let fixture = load_fixture();
    let pk_bytes = hex_to_bytes(&fixture.public_key_hex);
    let sk_bytes = hex_to_bytes(&fixture.secret_key_hex);
    let msg = hex_to_bytes(&fixture.message_hex);

    let signer = MlDsaSigner::from_bytes(&pk_bytes, &sk_bytes).expect("valid key pair");
    let sig = signer.sign(&msg).expect("sign succeeded");

    let verifier = MlDsaVerifier;
    assert!(
        verifier
            .verify(&pk_bytes, &msg, &sig)
            .expect("no crypto error"),
        "MlDsaSigner (from fixture key) must produce a verifiable signature"
    );
}
