use shell_core::{AccessListItem, Transaction};
use shell_primitives::{Address, Bytes, ShellHash, U256};

#[test]
fn sdk_hash_transaction_golden_vector_matches_chain() {
    let tx = Transaction {
        chain_id: 1337,
        nonce: 7,
        to: Some(Address::from([0x11; 20])),
        value: U256::from(0x1234u64),
        data: Bytes::from(vec![0xde, 0xad, 0xbe, 0xef]),
        gas_limit: 50_000,
        max_fee_per_gas: 1_000_000_000,
        max_priority_fee_per_gas: 250_000_000,
        access_list: Some(vec![AccessListItem {
            address: Address::from([0x22; 20]),
            storage_keys: vec![ShellHash::from([0x33; 32]), ShellHash::from([0x44; 32])],
        }]),
        tx_type: 3,
        max_fee_per_blob_gas: Some(0),
        blob_versioned_hashes: Some(vec![ShellHash::from([0x55; 32])]),
    };

    // Generated by shell-sdk hashTransaction() (includes fees, tx_type + blob fields in preimage):
    // 0xf5a14a12f556ff79fff941e944519f1c965b80e53c91503a676ff0a891ef0836
    let expected = ShellHash::from([
        0xf5, 0xa1, 0x4a, 0x12, 0xf5, 0x56, 0xff, 0x79, 0xff, 0xf9, 0x41, 0xe9, 0x44, 0x51, 0x9f,
        0x1c, 0x96, 0x5b, 0x80, 0xe5, 0x3c, 0x91, 0x50, 0x3a, 0x67, 0x6f, 0xf0, 0xa8, 0x91, 0xef,
        0x08, 0x36,
    ]);

    assert_eq!(tx.hash(), expected);
}
