[package]
name = "shell-fuzz"
version = "0.27.1"
edition = "2021"
license = "MIT"
publish = false

[workspace]

[patch.crates-io]
ark-relations = { path = "../deps/ark-relations" }

[lib]
name = "shell_fuzz"
path = "src/lib.rs"

[[bin]]
name = "fuzz_rlp"
path = "fuzz_targets/fuzz_rlp.rs"

[[bin]]
name = "fuzz_rpc"
path = "fuzz_targets/fuzz_rpc.rs"

[[bin]]
name = "fuzz_p2p_msg"
path = "fuzz_targets/fuzz_p2p_msg.rs"

[dependencies]
libfuzzer-sys = "0.4"
shell-core = { path = "../crates/core" }
shell-primitives = { path = "../crates/primitives" }
shell-rpc = { path = "../crates/rpc" }
alloy-rlp = { version = "0.3", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 3
debug = false
