[package]
name = "shell-node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
shell-primitives.workspace = true
shell-crypto.workspace = true
shell-core.workspace = true
shell-storage.workspace = true
shell-genesis = { path = "../genesis" }
shell-stark-prover = { path = "../stark-prover" }
shell-consensus = { path = "../consensus" }
shell-evm = { path = "../evm" }
shell-mempool = { path = "../mempool" }
shell-rpc = { path = "../rpc" }
shell-network = { path = "../network" }
alloy-rlp.workspace = true
tokio.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
thiserror.workspace = true
tracing.workspace = true
prometheus.workspace = true
hyper.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true

[dev-dependencies]
