[package]
name = "shell-mempool"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
shell-primitives.workspace = true
shell-crypto.workspace = true
shell-core.workspace = true
shell-pqvm = { path = "../pqvm" }
shell-storage = { path = "../storage" }
thiserror.workspace = true
parking_lot = { workspace = true }
serde_json.workspace = true
